-- eda is the name of the database and it stands for Exploratory Data Analysis.
USE eda;

SELECT COUNT(*)
FROM pizza_types
-- OUTPUT : 89 rows


SELECT COUNT(*)
FROM pizzas
-- OUTPUT : 2036 rows



SELECT COUNT(*)
FROM orders
-- OUTPUT : 916 rows
-- order_date and order_time are imported as VARCHAR(). The data type should be changed to date and time respectively



SELECT COUNT(*)
FROM order_details
-- OUTPUT : 2036 rows


/* Database Exploration */

 -- eda is the name of the database and it stands for Exploratory Data Analysis.
USE eda 
 
 
 
SHOW TABLES;
-- OUTPUT: Displays the table names of the tables in the eda database.alter


/* Displaying the columns present in each table in eda database. */

-- Table 1
DESCRIBE order_details

-- Table 2
DESCRIBE orders


-- Table 3
DESCRIBE pizza_types

-- Table 4
DESCRIBE pizzas


/ * Dimensions Exploration : Analyzing Dimensions */

-- Exploring all categories of pizzas from the pizza_types table.
SELECT DISTINCT(pizza_category)
FROM pizza_types

SELECT DISTINCT pizza_category, pizza_name
FROM pizza_types

-- Exploring the sizes of pizzas from the pizzas table.
SELECT DISTINCT(pizza_size)
FROM pizzas

SELECT DISTINCT pizza_name_id, pizza_size
FROM pizzas

-- Changing the data type of order_date and order_time from VARCHAR()

USE eda

DESCRIBE orders;
-- OUTPUT CHECKING : order_date and order_time are of VARCHAR() data type. We now need to change them to their respective datatypes.
 
 SELECT *
 FROM orders
 
 -- STEP 1. Updating the order_date and order_time columns to MySQL's standard temporal formats below:
 SET SQL_SAFE_UPDATES = 0;
 UPDATE orders
 SET
	order_date = STR_TO_DATE(order_date, '%d-%m-%Y'),
    order_time = STR_TO_DATE(order_time, '%H:%i:%s');
  SET SQL_SAFE_UPDATES = 1;  
  
-- STEP 2. Alter the column data types to their respective native types

ALTER TABLE orders
MODIFY COLUMN order_date DATE,
MODIFY COLUMN order_time TIME;

DESCRIBE orders
-- OUTPUT RESULTS: order_date and order_time are changed to their respective date and time data types.

SELECT *
FROM orders


 -- DATE EXPLORATION
 -- Identify the earliest and latest dates(boundaries).
 -- Understand the scope of data and the timespan.
 
 -- Find the date of the first and last order:
 SELECT MIN(order_date) as first_order_date,
		MAX(order_date) as last_order_date,
		DATEDIFF(MAX(order_date), MIN(order_date)) as Total_No_of_Days_between_Orders
 FROM orders
 
 
 -- MEASURES EXPLORATION
 -- Calculate the key metric of the business ( Big Numbers )
 -- Applying aggregate functions
 
 
 -- Calculating the total price i.e od.quantity * p.unit_price and Total Revenue:
 SELECT SUM(od.quantity * p.unit_price) as Total_Revenue
 FROM pizzas as p inner join order_details as od
 on p.pizza_id=od.pizza_id
 
 -- Calculating the number of pizzas sold:
 SELECT SUM(quantity) as Total_Quantity
 FROM order_details
 
 
 -- Average Selling Price
 SELECT AVG(unit_price) as Average_Price
 FROM pizzas
 
 
 -- Finding the total number of orders
 SELECT COUNT(DISTINCT order_id) as Total_Orders
 FROM orders
 
 -- Finding the total number of pizzas
 SELECT COUNT(DISTINCT pizza_id) as Total_No_of_Pizzas
 FROM pizzas
 
 
 -- Now generating a Report that shows all key metrics of the business
 SELECT 'Total Sales' as measure_name, SUM(od.quantity * p.unit_price) as measure_value
 FROM pizzas as p inner join order_details as od
 on p.pizza_id=od.pizza_id
 UNION ALL
 SELECT 'Total Quantity' as measure_name, SUM(quantity) as measure_value
 FROM order_details
 UNION ALL
 SELECT 'Average Price' as measure_name, AVG(unit_price) as measure_value
 FROM pizzas
 UNION ALL
 SELECT 'Total Orders' as measure_name, COUNT(DISTINCT order_id) as measure_value
 FROM orders
 UNION ALL
 SELECT 'Total No. of Pizzas' as measure_name, COUNT(DISTINCT pizza_id) as measure_value
 FROM pizzas
 
 
 -- Magnitude Analysis for Insights
 -- It is all about comparing the measure values by categories.
 -- Helps us understand the importance of different categories.
 
 
 -- Find total orders by pizza category
 SELECT pizza_category, COUNT(order_id) as Total_Orders
 FROM order_details, pizza_types
 GROUP BY pizza_category
 ORDER BY Total_Orders DESC
 

 -- Find the total pizzas by pizza category
 SELECT pizza_category, SUM(pizza_id) as Total_Pizzas
 FROM pizza_types as pt inner join pizzas as p
 on pt.pizza_name_id = p.pizza_name_id
 GROUP BY pizza_category
 ORDER BY Total_Pizzas DESC
 
 -- Find the average cost by category
 SELECT pizza_category, AVG(unit_price) as Average_Cost
 FROM pizza_types as pt inner join pizzas as p
 on pt.pizza_name_id = p.pizza_name_id
 GROUP BY pizza_category
 ORDER BY Average_Cost DESC
 
 -- Total Revenue generated by each category
 SELECT pt.pizza_category, SUM(od.quantity * p.unit_price) as Total_Revenue
 FROM order_details as od inner join pizzas as p
 on od.pizza_id = p.pizza_id
 inner join pizza_types as pt
 on p.pizza_name_id = pt.pizza_name_id
 GROUP BY pt.pizza_category
 ORDER BY Total_Revenue DESC
 
-- Distribution of sold pizzas across categories (i.e Total Quantity of Pizzas Sold by Categories)
SELECT pt.pizza_category, SUM(od.quantity) as Total_Quantity_Sold
FROM pizzas as p inner join pizza_types as pt
on p.pizza_name_id=pt.pizza_name_id
inner join order_details as od
on p.pizza_id = od.pizza_id
GROUP BY pt.pizza_category
ORDER BY Total_Quantity_Sold

-- Ranking Analysis : Top Performers and Bottom Performers
-- Which 5 Pizzas generate the highest revenue?
 SELECT pt.pizza_name, SUM(od.quantity * p.unit_price) as Total_Revenue
 FROM order_details as od inner join pizzas as p
 on od.pizza_id = p.pizza_id
 inner join pizza_types as pt
 on p.pizza_name_id = pt.pizza_name_id
 GROUP BY pt.pizza_name
 ORDER BY Total_Revenue DESC
 LIMIT 5

-- What are the 5 worst performing pizzas in terms of sales?
 SELECT pt.pizza_name, SUM(od.quantity * p.unit_price) as Total_Revenue
 FROM order_details as od inner join pizzas as p
 on od.pizza_id = p.pizza_id
 inner join pizza_types as pt
 on p.pizza_name_id = pt.pizza_name_id
 GROUP BY pt.pizza_name
 ORDER BY Total_Revenue ASC
 LIMIT 5


WITH RankedPizzas AS 
	( SELECT pt.pizza_name, SUM(od.quantity * p.unit_price) AS Total_Revenue,
	ROW_NUMBER() OVER (ORDER BY SUM(od.quantity * p.unit_price) DESC) AS rank_pizzas
	FROM order_details AS od INNER JOIN pizzas AS p
	ON od.pizza_id = p.pizza_id 
	INNER JOIN pizza_types AS pt
	ON p.pizza_name_id = pt.pizza_name_id 
	GROUP BY pt.pizza_name ) 
    
 SELECT pizza_name, Total_Revenue, rank_pizzas 
 FROM RankedPizzas
 WHERE rank_pizzas <= 5;
 
 
 



 



